<div id="contentDiv" onmouseover="getTop().stopPropagation(event);" onclick="getTop().preSwapLink(event, 'spam', 'ZL0903-PUDqVicdDzuE80wZFh1Db58');" style="position:relative;font-size:14px;height:auto;padding:15px 15px 10px 15px;z-index:1;zoom:1;line-height:1.7;overflow:hidden;" class="body">    <div class="" id="qm_con_body"><div id="mailContentContainer" class="qmbox qm_con_body_content"><div>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">从前从前，有四个少年，其中一对是好兄弟，一直相爱相杀，一起星辰大海，开创了伟大的帝国，他们叫西班牙与葡萄牙；另一位是文艺青年，是西方文明的发起者，他叫希腊；最后一个少年是一位骁勇善战的英雄，被人称为“斗牛骑士”</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">----<font face="宋体">西班牙。</font></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">这四位少年的辉煌战绩加起来就是大半部欧洲的兴衰史。靠着过去的丰功伟绩，他们开始过着没羞没臊的幸福生活，也因此变得越来越懒惰。于是人们将葡萄牙（<font face="Times New Roman">Portugal</font><font face="宋体">）、意大利（</font><font face="Times New Roman">Italy</font><font face="宋体">）、希腊（</font><font face="Times New Roman">Greece</font><font face="宋体">）与西班牙（</font><font face="Times New Roman">Spain</font><font face="宋体">）这四位少年的首字母接成一个词——“</font><font face="Times New Roman">pigs</font><font face="宋体">”，俗称“欧洲四猪。”</font></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><!--?xml:namespace prefix="o" ns="urn:schemas-microsoft-com:office:office"--><!--?xml:namespace--><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/1.jpg" width="311" height="220"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">与此同时，在遥远的东方，有一位屠龙少年。他天赋异禀，家道殷实。后来因不思进取，被外来的洋学生吊打，当众羞辱，甚至逼着变卖家产。少年卧薪尝胆，奋发图强，与其他四位好基友靠搬砖起家，一起打怪升级，茁壮成长，号称“金砖四侠。”</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/2.jpg" width="307" height="220"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">时光荏苒，岁月如梭，猪越吃越胖，而少年也早已不是当年的少年。</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">猪们享受着舒适的生活，但是臃肿的体态已经让他们行动越来越吃力，农场的存粮也越来越少，可是他们又不愿意节衣缩食，猪急了也是会咬人的。于是希腊猪脑洞大开，向德国索要<font face="Times New Roman">1600</font><font face="宋体">亿欧元（相当于希腊一年国内生产总值的八成）二战赔偿且不含利息，以解决希腊严峻的债务危机。</font></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">全世界的小伙伴听说后的表情是这样的</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/3.jpg" width="202" height="213"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">以德国为首的欧盟已多次贷款援助希腊，希腊赖账不说，还义正言辞的要求债主还钱。这得多无耻啊？！</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">中国少年此刻瞟了一眼日本，心想：你该赔我的银子应该也不少吧…………</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">默克尔当然严词拒绝，然后希腊猪绝望了，摸着瘦了一圈的肚子，又急中生智想出了丧权辱国的一招：卖肉。是的，卖肉…………希腊以黄金签证向外国投资者敞开大门：</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">只要在希腊买下一套25万欧元的房子，约合人民币165万元以上的房产所有权，主申请人及其一家人(包括其配偶和21岁以下的子女)就可以申请得到希腊5年居留许可，自由通行27个申根国家；房产不出售，居留即可继续，5年到期后更新，直到入籍；入籍后将可自由出入全球169个国家，该通行国家的数目仅次于英美等国。但是，</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">希腊</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">依旧无力回天，</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">五年来，房价下跌了五成，一些海景豪宅价格在近一年的跌幅甚至高达35%，简直跌破天际。</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/4.jpg" width="554" height="369"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">我已经开始想象广场大妈抢占爱琴海，五星红旗飘扬在希腊国土上的场景。至此，我不禁为资本主义国家的腐败堕落而扼腕叹息，以身在社会主义国家而感到万分庆幸。万万没想到，在此背景下发生的一件事情，击碎了我的三观。</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">事情源于我的一个好基友，他最近发的朋友圈是这样的<font face="Times New Roman">:</font></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/5.jpg" width="320" height="568"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"></span>&nbsp;</p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">在好奇心的驱使下，我去问了他，以下是对话截图：</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/5.jpg" width="533" height="948"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="TEXT-INDENT: 21pt; mso-char-indent-count: 2.0000"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">你知道这是什么概念吗？北京最新房价已经达到每平方米<font face="Times New Roman"><span style="border-bottom:1px dashed #ccc;z-index:1" t="7" onclick="return false;" data="32719">32719</span></font><font face="宋体">元</font></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">/</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: Arial; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-fareast-font-family: 宋体">㎡</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">，而且还在上涨。</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="TEXT-INDENT: 21pt; mso-char-indent-count: 2.0000"><img src="http://email.test.abc123.gxtkr.com/img/6.jpg" width="554" height="244"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 'Times New Roman'; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-fareast-font-family: 宋体"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="TEXT-INDENT: 21pt; mso-char-indent-count: 2.0000"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">&nbsp;&nbsp;&nbsp; </span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">帝都离我们太遥远，我手贱搜了一下南宁的房价，已经快逼近一万大关，而且还有继续上涨的趋势。</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="TEXT-INDENT: 21pt; mso-char-indent-count: 2.0000"><img src="http://email.test.abc123.gxtkr.com/img/7.jpg" width="554" height="261"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 'Times New Roman'; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-fareast-font-family: 宋体"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="TEXT-INDENT: 21pt; mso-char-indent-count: 2.0000"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 'Times New Roman'; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-fareast-font-family: 宋体"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">这一次，我感受到了这个世界深深的恶意。打从那一刻起，我和他已经走上了完全不同的人生轨迹，大家来感受一下：</span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">他住的地方</span><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/8.jpg" width="554" height="370"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">此刻的我</span><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/9.jpg" width="553" height="415"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">因为获得希腊居留许可，能自由通行27个申根国家，所以他的假期是这样的</span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/10.jpg" width="554" height="370"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/11.jpg" width="554" height="368"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">此刻的我</span><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/12.jpg" width="554" height="408"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">………………………………</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">下班后的他</span><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/13.jpg" width="548" height="308"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">此刻的我</span><span style="FONT-SIZE: 14pt; FONT-FAMILY: 黑体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/14.jpg" width="575" height="184"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">………………………………</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/15.jpg" width="202" height="213"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"></span>&nbsp;</p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">对，我就故事里那个屠龙少年，我还在一边搬砖，一边打怪升级，而他就是那头过着没羞没臊生活的猪。故事本该到此结束，但是看了他发的最近一张朋友圈：</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/16.jpg" width="320" height="568"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"></span>&nbsp;</p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">我毅然决然的拉黑了他，此生再无交集。</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/17.jpg" width="275" height="207"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">在拉黑他前，我特地问了他投资移民的方法，他说：“有钱就好，我英语又不好，都是叫中介帮办的。”然后给了我以下公司信息，也是当年帮他出国的公司。这都不是重点，重点是有意向移民的朋友，你家还缺配偶吗？读过大学会点英语那种…………</span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"></span>&nbsp;</p><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: bold; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">广西一方海外信息服务有限公司</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">广西一方海外信息服务有限公司成立于<font face="Times New Roman">1999</font><font face="宋体">年</font><font face="Times New Roman">4</font><font face="宋体">月，公司主要业务包括：国学生签证、探亲旅游签证、商务签证、海外移民、各种短期签证、境外就业服务等。公司具有高素质、高效能的业务团队，高成功率和高诚信度是公司的服务宗旨。</font></span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">电话：<span style="border-bottom:1px dashed #ccc;z-index:1" t="7" onclick="return false;" data="0771-5851883">0771-5851883</span>/<span style="border-bottom:1px dashed #ccc;z-index:1" t="7" onclick="return false;" data="5852032">5852032</span>/<span style="border-bottom:1px dashed #ccc;z-index:1" t="7" onclick="return false;" data="5853229">5853229</span></span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">传真：<span style="border-bottom:1px dashed #ccc;z-index:1" t="7" onclick="return false;" data="4008266163-16080">4008266163-16080</span></span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">邮箱：<a href="mailto:yifangvisa@yifangvisa.com" target="_blank">yifangvisa@y<wbr>ifangvisa.co<wbr>m</a></span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">邮编：<span style="border-bottom:1px dashed #ccc;z-index:1" t="7" onclick="return false;" data="530000">530000</span></span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">地址：民族大道131号航洋国际城2号楼恒富中心8楼</span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: normal; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">公司官网网址：</span><span><a href="http://www.yifangvisa.com/" target="_blank"><span class="15" style="FONT-SIZE: 12pt; TEXT-DECORATION: underline; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; text-underline: single">http://www.yifangvisa.com/</span></a></span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal" style="MARGIN-BOTTOM: 0pt; PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN-TOP: 0pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; MARGIN-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd"><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt">二维码：</span><span style="FONT-SIZE: 12pt; FONT-FAMILY: 微软雅黑; COLOR: rgb(51,51,51); mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p>
<p class="MsoNormal"><img src="http://email.test.abc123.gxtkr.com/img/20.jpg" width="312" height="312"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"></span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>
<p class="MsoNormal" style="PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN: 0pt 0pt 0pt -18pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd; mso-para-margin-left: 0.0000gd"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: bold; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">广</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p></o:p></span></p><p></p>
<p class="MsoNormal" style="PADDING-BOTTOM: 0pt; PADDING-TOP: 0pt; PADDING-LEFT: 0pt; MARGIN: 0pt 0pt 0pt -18pt; LINE-HEIGHT: 33.75pt; PADDING-RIGHT: 0pt; mso-pagination: widow-orphan; mso-para-margin-right: 0.0000gd; mso-para-margin-left: 0.0000gd"><span style="FONT-SIZE: 14pt; FONT-FAMILY: 微软雅黑; BACKGROUND: rgb(255,255,255); TEXT-TRANSFORM: none; FONT-WEIGHT: bold; COLOR: rgb(51,51,51); FONT-STYLE: normal; LETTER-SPACING: 0pt; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-shading: rgb(255,255,255)">广</span><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 宋体; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"><span style="FONT-SIZE: 10.5pt; FONT-FAMILY: 'Times New Roman'; mso-spacerun: 'yes'; mso-font-kerning: 1.0000pt; mso-fareast-font-family: 宋体"><o:p>&nbsp;</o:p></span></p></o:p></span></div></div></div><!-- --><style>#mailContentContainer .txt {height:auto;}</style>  </div>